# Generated by Django 5.0.6 on 2024-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0002_joblisting_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_link',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
