# Generated by Django 5.0.6 on 2024-09-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0003_joblisting_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_origin',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
